server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: SeatReservation

  datasource:
    url: jdbc:mysql://localhost:3307/seat_reservation?useSSL=false&serverTimezone=Asia/Shanghai&connectionCollation=utf8mb4_unicode_ci&allowPublicKeyRetrieval=true
    username: root
    password: 622824
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual  # 启用手动 ACK 模式，防止消息丢失

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
jwt:
  secret: U2VhdFJlc2VydmF0aW9uU3lzdGVtQnlMRU9IRVJPMjAyNQ==
  expiration: 604800000