server:
  port: 8080

spring:
  application:
    name: SeatReservation

  datasource:
    url: jdbc:mysql://mysql:3306/seat_reservation?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 622824
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis
      port: 6379

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual  # 启用手动 ACK 模式，防止消息丢失

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
jwt:
  secret: U2VhdFJlc2VydmF0aW9uU3lzdGVtQnlMRU9IRVJPMjAyNQ==
  expiration: 604800000
